### ISSUE TITLE
All about maestro in an organization

### ISSUE THREAD

**Issue by Neustradamus** [maestro-os/maestro#13]
Dear @llenotre,

In first, I wish you a Happy New Year 2024!

It is a good project, I think, it will be better to have all repositories into an organization than a personal account.

Can you look?

**Comment by llenotre** [comment]
Hi,

Thank you, happy new year to you too!

I already thought about having Maestro in an organization. That would be easier for sorting everything correctly. It would also be a lot easier for Github Actions runners, as it is not currently possible to share a runner across projects unless they are in the same organization.

However, the problem is: if I want to enable Github Sponsors one day, Github is going to take a fee on donations, which does not apply for a personal account.

**Comment by llenotre** [comment]
Hi,

I finally decided to move Maestro to its [own organization](https://github.com/maestro-os)!

**Comment by Neustradamus** [comment]
@llenotre: Good job!

Can you add you in public here?
- https://github.com/orgs/maestro-os/people

**Comment by llenotre** [comment]
You are right! Done!
